[Eth]
NetworkId = 20220521
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
GasFloor = 0
GasCeil = 0
GasPrice = 0
Recommit = 0
Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60


[Node]
DataDir = "node"
InsecureUnlockAllowed = true
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "127.0.0.1"
HTTPPort = 8575
HTTPVirtualHosts = ["*"]
HTTPModules = ["debug","eth", "net", "web3", "txpool", "parlia"]
WSPort = 8576
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 20
NoDiscovery = true

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000
